Repository Dianevera/heart-prediction, pull requests merged in 2021-11, with the labels that each got.

#6 2 make powerpoint for planning of project
  Documentation/Study of posibilities.pptx
  README.md
Labels: To review

#14 11 decision tree model design
  data_cleaning.ipynb
  decision_tree_model.ipynb
  decision_tree_utilisation.ipynb
Labels: merged

#16 15 package the decison tree
  DecisionTree/DecisionTree.py
  DecisionTree/Node.py
  DecisionTree/__init__.py
  decision_tree_model.ipynb
  decision_tree_notebook.ipynb
  decision_tree_utilisation.ipynb
Labels: merged

#22 20 DecisionTree testsuite
  README.md
  tests/Test_DecisionTree.py
  tests/Test_DecisionTreeAccuracy.py
  tests/tests_pkl/actual_decisionTree_accuracies.pkl
  tests/tests_pkl/test_decisionTree_accuracies.pkl
Labels: To merge

#21 15 package the decison tree
  DecisionTree/DecisionTree.py
  decision_tree_notebook.ipynb
Labels: To review

#25 10 regression model design
  .gitignore
  LogisticRegression/HeartDiseaseDataset.py
  LogisticRegression/LogisticRegression.py
  LogisticRegression/LogisticRegressionUtils.py
  LogisticRegression/Trainer.py
  LogisticRegression/__init__.py
  best_weights/LogisticRegression_accuracies.pkl
  best_weights/logistic_regression_weights/logistic_regression_ANGINA.pt
  best_weights/logistic_regression_weights/logistic_regression_ANYCHD.pt
  best_weights/logistic_regression_weights/logistic_regression_CVD.pt
  best_weights/logistic_regression_weights/logistic_regression_DEATH.pt
  best_weights/logistic_regression_weights/logistic_regression_HOSPMI.pt
  best_weights/logistic_regression_weights/logistic_regression_HYPERTEN.pt
  best_weights/logistic_regression_weights/logistic_regression_MI_FCHD.pt
  best_weights/logistic_regression_weights/logistic_regression_STROKE.pt
  compute_accuracy_pkl_with_weights.py
  current_accuracies/decision_tree/decisionTree_accuracies.pkl
  current_accuracies/logistic_regression/LogisticRegression_accuracies.pkl
  current_accuracies/logistic_regression/logistic_regression_weights/logistic_regression_ANGINA.pt
  current_accuracies/logistic_regression/logistic_regression_weights/logistic_regression_ANYCHD.pt
  current_accuracies/logistic_regression/logistic_regression_weights/logistic_regression_CVD.pt
  current_accuracies/logistic_regression/logistic_regression_weights/logistic_regression_DEATH.pt
  current_accuracies/logistic_regression/logistic_regression_weights/logistic_regression_HOSPMI.pt
  current_accuracies/logistic_regression/logistic_regression_weights/logistic_regression_HYPERTEN.pt
  current_accuracies/logistic_regression/logistic_regression_weights/logistic_regression_MI_FCHD.pt
  current_accuracies/logistic_regression/logistic_regression_weights/logistic_regression_STROKE.pt
  logistic_regression.ipynb
  tests/Test_DecisionTree.py
  tests/Test_DecisionTreeAccuracy.py
  tests/Test_LogisticRegressionAccuracy.py
  tests/tests_pkl/decision_tree/decisionTree_accuracies.pkl
  tests/tests_pkl/logistic_regression/LogisticRegression_accuracies.pkl
  tests/tests_pkl/test_decisionTree_accuracies.pkl
Labels: merged

#31 26 refacto logistic regression model
  LogisticRegression/HeartDiseaseDataset.py
  LogisticRegression/LogisticRegression.py
  LogisticRegression/LogisticRegressionUtils.py
  LogisticRegression/Trainer.py
  LogisticRegression/__init__.py
  LogisticRegression/compute_class_weights.py
  LogisticRegression/compute_min_max.py
  LogisticRegression/create_dataloaders.py
  LogisticRegression/multiple_labels_trainer.py
  LogisticRegression/save_and_predict.py
  best_weights/LogisticRegression_accuracies.pkl
  best_weights/logistic_regression_weights/logistic_regression_ANGINA.pt
  best_weights/logistic_regression_weights/logistic_regression_MI_FCHD.pt
  compute_accuracy_pkl_with_weights.py
  compute_save_compare_accuracies.py
  current_accuracies/logistic_regression/LogisticRegression_accuracies.pkl
  current_accuracies/logistic_regression/logistic_regression_weights/logistic_regression_ANGINA.pt
  current_accuracies/logistic_regression/logistic_regression_weights/logistic_regression_ANYCHD.pt
  current_accuracies/logistic_regression/logistic_regression_weights/logistic_regression_CVD.pt
  current_accuracies/logistic_regression/logistic_regression_weights/logistic_regression_DEATH.pt
  current_accuracies/logistic_regression/logistic_regression_weights/logistic_regression_HOSPMI.pt
  current_accuracies/logistic_regression/logistic_regression_weights/logistic_regression_HYPERTEN.pt
  current_accuracies/logistic_regression/logistic_regression_weights/logistic_regression_MI_FCHD.pt
  current_accuracies/logistic_regression/logistic_regression_weights/logistic_regression_STROKE.pt
  logistic_regression.ipynb
  tests/tests_pkl/logistic_regression/LogisticRegression_accuracies.pkl
Labels: merged

#35 34 [FIX] fix import
  src/Data_analysis.ipynb
  src/decision_tree_notebook.ipynb
  src/logistic_regression.ipynb
Labels: To review, To merge
